### ISSUE TITLE
My activity log dashboard spammed by Crawler

### ISSUE THREAD

**Issue by davymaish** [jeremykenedy/laravel-logger#154]
Thanks for the wonderful package
After taking my website to production environment, activity logs dashboard has been spammed by Crawler activity in that it has become totally impossible to monitor user activity. 
![Screenshot_20230210-090335-498](https://user-images.githubusercontent.com/57931405/218015039-f52f89d2-4215-4c28-be52-43d83f141241.png)

I have two questions. Does this crawler activities show any danger signs or does it pose any threat to my application? If no, how can I disable so that crawler activities are not recorded? Thanks in advance.

**Comment by jeremykenedy** [comment]
That's a lot crawling and may be an indication of a potential ddos attack. 

It's still activity within the system so it will be recorded. In order to disable it the logic would need to be changed in so when it is a crawler it will not record. 

It's a good opportunity for a PR that will extend to the config/env to disable this. The out the box should be it's enabled so if a PR for this does arise it should have the option to disable this but still remain enabled by default.

**Comment by davymaish** [comment]
I hope you could come up with a solution for this. If this crawler indicates a ddos attack, do you have any recommendations on how to stop it?

**Comment by jeremykenedy** [comment]
This package isn't to protect against a ddos attack, you would probably want to adjust the rate limiting in your app.

If one was to look where the logic is to detect if it is a crawler and put in logic to check against the config file which would extend from env you would do so around here:

https://github.com/jeremykenedy/laravel-logger/blob/master/src/App/Http/Traits/ActivityLogger.php#L32

but the default logic would be false it  ales it 100% backwards compatible.
